# Generated by Django 5.1.1 on 2025-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_info',
            name='cpassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signup_info',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup_info',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signup_info',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='signup_info',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
