# Generated by Django 5.1.1 on 2024-12-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='additional_features',
            new_name='additional_features1',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='available_sizes',
            new_name='available_sizes1',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_review',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='image_url',
        ),
        migrations.AddField(
            model_name='products_data',
            name='additional_features2',
            field=models.TextField(default='No additional features available'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='additional_features3',
            field=models.TextField(default='No additional features available'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='additional_features4',
            field=models.TextField(default='No additional features available'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='available_sizes2',
            field=models.CharField(default='No size available', max_length=100),
        ),
        migrations.AddField(
            model_name='products_data',
            name='available_sizes3',
            field=models.CharField(default='No size available', max_length=100),
        ),
        migrations.AddField(
            model_name='products_data',
            name='available_sizes4',
            field=models.CharField(default='No size available', max_length=100),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review_1',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review_2',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review_3',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review_4',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer_name_1',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer_name_2',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer_name_3',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer_name_4',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products_data',
            name='delivery_options',
            field=models.CharField(default='No size available', max_length=100),
        ),
    ]
