# Generated by Django 5.1.1 on 2025-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_additional_features_products_data_additional_features1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='customer_review_1',
            new_name='customer_review',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='additional_features2',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='additional_features3',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='additional_features4',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='available_sizes4',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_review_2',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_review_3',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_review_4',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_reviewer_name_1',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_reviewer_name_2',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_reviewer_name_3',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='customer_reviewer_name_4',
        ),
        migrations.AddField(
            model_name='products_data',
            name='image_url',
            field=models.TextField(default='No image address given'),
        ),
    ]
