# Generated by Django 5.1.1 on 2025-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_customer_review_1_products_data_customer_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='available_sizes1',
            new_name='_1kg',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='available_sizes2',
            new_name='_2kg',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='available_sizes3',
            new_name='_5kg',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='discount_percent',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='products_data',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
