# Generated by Django 5.1.1 on 2025-01-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_available_sizes1_products_data__1kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='additional_features1',
            new_name='additional_features',
        ),
    ]
