# Generated by Django 5.1.1 on 2025-02-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_rename_additional_features1_products_data_additional_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='_2kg',
            new_name='available_size1',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='_5kg',
            new_name='available_size2',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='customer_review',
            new_name='customer_review1',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='additional_features',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='description',
            new_name='description_2',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='npk_content',
            new_name='npk_ratio',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='_1kg',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='weight',
        ),
        migrations.AddField(
            model_name='products_data',
            name='additional_feature1',
            field=models.TextField(default='No additional features available'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='additional_feature2',
            field=models.TextField(default='No additional features available'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='additional_feature3',
            field=models.TextField(default='No additional features available'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='available_size3',
            field=models.CharField(default='No size available', max_length=100),
        ),
        migrations.AddField(
            model_name='products_data',
            name='available_size4',
            field=models.CharField(default='No size available', max_length=100),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review2',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review3',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_review4',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer1',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer2',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer3',
            field=models.CharField(default='No review available', max_length=50),
        ),
        migrations.AddField(
            model_name='products_data',
            name='customer_reviewer4',
            field=models.CharField(default='No review available', max_length=50),
        ),
    ]
