# Generated by Django 5.1.1 on 2025-02-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
