# Generated by Django 5.1.1 on 2025-02-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_order_created_at_alter_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
