# Generated by Django 5.1.1 on 2025-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(max_length=20, verbose_name='Overall Satisfaction')),
                ('prod_looks', models.CharField(max_length=10, verbose_name='How was Product Looks')),
                ('process', models.CharField(max_length=20, verbose_name='Process Experience')),
                ('deliv_satisfy', models.CharField(max_length=20, verbose_name='Satisfaction about delivery options')),
                ('cust_rate', models.CharField(max_length=20, verbose_name='Review about customer serviece')),
                ('suggestion', models.TextField(default=None, null=True, verbose_name='Suggestions')),
                ('recommend', models.CharField(max_length=10, verbose_name='Would you recomment the site')),
                ('rating', models.IntegerField(verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('review', models.TextField(verbose_name='Message')),
                ('rate', models.IntegerField(verbose_name='Rating')),
            ],
        ),
    ]
